const MAX_VISIBLE = 4;
const SINGLE_WIDTH = 416;
const COMPACT_COMPARISON_WIDTH = 480;
const COLLAPSED_WIDTH = 40;
const COLUMN_WIDTH = 352;
const MIN_RESIZE_WIDTH = 200;
const MAX_RESIZE_RATIO = 0.8;

export const RES_WIDTH = 92;
export const CHAIN_HEIGHT = 116;
export const MAX_RENDERED_RESIDUES = 600;
